# Generated by Django 3.0.5 on 2020-07-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200727_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='salutation',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('1', 'Dental'), ('2', 'Neuro'), ('3', 'Child'), ('4', 'Bone'), ('5', 'General'), ('6', 'Heart'), ('7', 'Eyes'), ('8', 'Gyno')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Salutation',
        ),
    ]
