# Generated by Django 3.0.5 on 2020-07-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200727_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('Dental', '1'), ('Neuro', '2'), ('Child', '3'), ('Bone', '4'), ('General', '5'), ('Heart', '6'), ('Eyes', '7'), ('Gyno', '8')], max_length=100, null=True),
        ),
    ]
