# Generated by Django 3.0.5 on 2020-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200727_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='token',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
