# Generated by Django 3.0.5 on 2020-07-27 08:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200727_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='firstName'),
        ),
    ]
